# Generated by Django 5.2.8 on 2026-06-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_messageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='last_message_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
